name: build package

on:
  schedule:
    - cron: '30 9 * * 0,4'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      openwrt_versions:
        description: "OpenWrt version(s)"
        type: string
        required: true
        default: "23.05.3 25.12.0"

jobs:
  generate-target-matrix:
    runs-on: ubuntu-24.04
    outputs:
      build-matrix: ${{ steps.generate-target-matrix.outputs.BUILD_MATRIX }}
    env:
      OPENWRT_RELEASES: ${{ inputs.openwrt_versions || vars.DEFAULT_OPENWRT_VERSIONS }}
    steps:
      - name: checkout openwrt-crossbuild-env
        uses: actions/checkout@v6
        with:
          path: openwrt-crossbuild-env
          repository: defanator/openwrt-crossbuild-env
          ref: ci
          fetch-depth: 0

      - name: checkout openwrt-loki-exporter
        uses: actions/checkout@v6
        with:
          path: openwrt-loki-exporter
          fetch-depth: 0

      - name: generate target matrix
        id: generate-target-matrix
        env:
          OPENWRT_TARGET_MATRIX_CONFIG: ci/target-matrix-config.yaml
        run: |
          set -x
          cd openwrt-loki-exporter
          make generate-target-matrix >> "$GITHUB_OUTPUT"

  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch }} :: ${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }} openwrt build"
    runs-on: ubuntu-24.04
    needs: generate-target-matrix
    strategy:
      fail-fast: false
      matrix:
        build_env: ${{ fromJson(needs.generate-target-matrix.outputs.build-matrix) }}

    env:
      OPENWRT_RELEASE: ${{ matrix.build_env.tag }}
      OPENWRT_ARCH: ${{ matrix.build_env.pkgarch }}
      OPENWRT_TARGET: ${{ matrix.build_env.target }}
      OPENWRT_SUBTARGET: ${{ matrix.build_env.subtarget }}
      OPENWRT_VERMAGIC: ${{ matrix.build_env.vermagic }}

    steps:
      - name: checkout openwrt-crossbuild-env
        uses: actions/checkout@v6
        with:
          path: openwrt-crossbuild-env
          repository: defanator/openwrt-crossbuild-env
          ref: ci
          fetch-depth: 0

      - name: checkout openwrt-loki-exporter
        uses: actions/checkout@v6
        with:
          path: openwrt-loki-exporter
          fetch-depth: 0

      - name: checkout openwrt
        uses: actions/checkout@v6
        with:
          path: openwrt
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: build package
        id: build-package
        env:
          OPENWRT_SRCDIR: ../openwrt
        run: |
          set -x
          cd openwrt-loki-exporter
          make show-env
          make export-env >> $GITHUB_OUTPUT
          time -p make prepare
          time -p make fix-host-symlinks
          time -p make package
          make prepare-artifacts

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: loki-exporter-${{ steps.build-package.outputs.version_str }}_v${{ matrix.build_env.tag }}_${{ matrix.build_env.pkgarch }}_${{ matrix.build_env.target }}_${{ matrix.build_env.subtarget }}
          path: loki_exporter_artifacts/*
